---
name: VyOS Rolling + Tailscale

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

# Some code borrowed from https://github.com/onedr0p/vyos/blob/main/.github/workflows/rolling.yml
env:
  VYOS_URL: https://github.com/vyos/vyos-build
  VYOS_BRANCH: current
  VYOS_ARCH: amd64
  VYOS_BUILD_BY: github-actions@github.com
  VYOS_BUILD_TYPE: release
  VYOS_VERSION: 1.4-rolling

jobs:
  build-iso:
    runs-on: ubuntu-20.04
    container:
      image: vyos/vyos-build:current
      options: --privileged
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Tools
        run: sudo apt install -y make

      - name: Run setup actions
        run: make prepare

      - name: Setup variables
        id: vars
        run: |
          build_date=$(date +%Y%m%d%H%M)
          echo "iso-name=${{ env.VYOS_VERSION }}-${build_date}-${{ env.VYOS_ARCH }}" >> "$GITHUB_OUTPUT"
          echo "tag-name=${{ env.VYOS_VERSION }}-${build_date}" >> "$GITHUB_OUTPUT"
      
      - name: Configure
        working-directory: vyos-build
        run: |
          ./build-vyos-image iso \
              --architecture ${{ env.VYOS_ARCH }} \
              --build-by ${{ env.VYOS_BUILD_BY }} \
              --build-type ${{ env.VYOS_BUILD_TYPE }} \
              --build-comment "VyOS with Tailscale" \
              --version ${{ steps.vars.outputs.tag-name }} \
              --custom-apt-key ../tailscale.gpg \
              --custom-apt-entry "deb https://pkgs.tailscale.com/stable/debian bullseye main" \
              --custom-package "tailscale"

      - uses: actions/upload-artifact@v3
        with:
          name: vyos-iso
          path: "./vyos-build/build/vyos-${{ steps.vars.outputs.iso-name }}.iso"
          retention-days: 1

  build-qemu:
    runs-on: ubuntu-latest
    needs: build-iso
    container:
      image: ubuntu:latest
      options: --privileged
    steps:

      - name: Download vyos iso artifact
        uses: actions/download-artifact@v3

      - name: Setup Tools
        run: apt update && DEBIAN_FRONTEND=noninteractive apt install -y python3 ansible git

      - name: Setup variables
        id: vars
        run: |
          build_date=$(ls -1 vyos-iso | awk -F'.' '{print $1.$2}' | awk -F'-' '{print $4}')
          echo "iso-name=${{ env.VYOS_VERSION }}-${build_date}-${{ env.VYOS_ARCH }}" >> "$GITHUB_OUTPUT"
          echo "tag-name=${{ env.VYOS_VERSION }}-${build_date}" >> "$GITHUB_OUTPUT"

      - name: Clone ansible playbooks
        uses: actions/checkout@v3
        with:
          path: vyos-vm-images
          repository: 'vyos/vyos-vm-images'

      - name: Run ansible playbook to generate qemu image
        working-directory: vyos-vm-images
        run: |
          sed -i '/download-iso/d' ./qemu.yml
          sed -i -e '18,19d' ./roles/install-grub/tasks/main.yml
          ansible-playbook qemu.yml -e "iso_local=../vyos-iso/vyos-${{ steps.vars.outputs.iso-name }}.iso" \
                -e disk_size=16 -e cloud_init=true -e cloud_init_ds=NoCloud,ConfigDrive,None -e guest_agent=qemu \
                -e enable_dhcp=true -e enable_ssh=true -e parttable_type=gpt
          mv /tmp/vyos-*-qemu.qcow2 "./vyos-qemu-${{ steps.vars.outputs.iso-name }}.qcow2"

      - uses: actions/upload-artifact@v3
        with:
          name: vyos-qemu
          path: "./vyos-vm-images/vyos-qemu-${{ steps.vars.outputs.iso-name }}.qcow2"
          retention-days: 1

  create-release:
    runs-on: ubuntu-latest
    needs: build-qemu
    permissions:
      contents: write
    steps:

      - name: Download vyos artifacts
        uses: actions/download-artifact@v3

      - name: Setup variables
        id: vars
        run: |
          build_date=$(ls -1 vyos-iso | awk -F'.' '{print $1.$2}' | awk -F'-' '{print $4}')
          echo "iso-name=${{ env.VYOS_VERSION }}-${build_date}-${{ env.VYOS_ARCH }}" >> "$GITHUB_OUTPUT"
          echo "tag-name=${{ env.VYOS_VERSION }}-${build_date}" >> "$GITHUB_OUTPUT"

      - uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.vars.outputs.tag-name }}"
          artifacts: "./vyos-iso/vyos-${{ steps.vars.outputs.iso-name }}.iso, ./vyos-qemu/vyos-qemu-${{ steps.vars.outputs.iso-name }}.qcow2"
          artifactErrorsFailBuild: true
          body: |
            Official VyOS Changelog:
            https://docs.vyos.io/en/latest/changelog/1.4.html
